# Generated by Django 4.2.9 on 2024-02-15 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('release_date', models.DateField()),
                ('actors', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('action', 'Action'), ('drama', 'DRAMA'), ('comedy', 'COMEDY'), ('romance', 'ROMANCE'), ('adventure', 'ADVENTURE'), ('thriller', 'THRILLER')], default='1', max_length=15)),
                ('img', models.ImageField(upload_to='gallery')),
                ('trailer', models.URLField(blank=True, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
