# Generated by Django 4.2.9 on 2024-02-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_movie_category_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product',
            new_name='movie',
        ),
    ]
