# Generated by Django 4.2.9 on 2024-02-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_rename_comment_body_comment_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment_body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='commenter_name',
        ),
    ]
